### ISSUE TITLE
摄像头问题

### ISSUE THREAD

**Issue by baiRookie** [zerochl/MagicShow#2]
今天研究了一下，发现在前置摄像头的情况下，会出现一些问题

**Comment by baiRookie** [comment]
前置摄像头加滤镜拍出的照片从中间上下颠倒了，有什么解决方法吗？找了半天没有发现解决方法

**Comment by zerochl** [comment]
拍摄之后会离屏渲染出一张bitmap，此处会做角度翻转

**Comment by zerochl** [comment]
前置摄像头bug已经解了，pull一下代码吧

**Comment by baiRookie** [comment]
谢谢大神的支持，学到很多，虽然很多东西仍旧不太懂
